ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "avatarUrl" TEXT;

ALTER TABLE "WappiLine" ALTER COLUMN "groupId" DROP NOT NULL;

ALTER TABLE "WappiLine" DROP CONSTRAINT IF EXISTS "WappiLine_groupId_fkey";
ALTER TABLE "WappiLine" ADD CONSTRAINT "WappiLine_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "Group"("id") ON DELETE SET NULL ON UPDATE CASCADE;
