ALTER TABLE "Message" ADD COLUMN IF NOT EXISTS "caption" TEXT;
ALTER TABLE "Message" ADD COLUMN IF NOT EXISTS "fileName" TEXT;
ALTER TABLE "Message" ADD COLUMN IF NOT EXISTS "mimeType" TEXT;
ALTER TABLE "Message" ADD COLUMN IF NOT EXISTS "mediaUrl" TEXT;
