services:
  backend:
    build:
      context: ./repo
      dockerfile: apps/backend/Dockerfile
    image: ${IMAGE_BACKEND:-fintech-backend:prod}

  admin-panel:
    build:
      context: ./repo
      dockerfile: apps/admin-panel/Dockerfile
    image: ${IMAGE_ADMIN:-fintech-admin:prod}

  user-panel:
    build:
      context: ./repo
      dockerfile: apps/user-panel/Dockerfile
    image: ${IMAGE_USER:-fintech-user:prod}