services:
  backend:
    image: ${IMAGE_BACKEND:-fintech-backend:prod}
    env_file: .env
    environment:
      VIRTUAL_HOST: api.msg.fintech-consult.ru
      LETSENCRYPT_HOST: api.msg.fintech-consult.ru
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      VIRTUAL_PORT: 3000
    expose:
      - "3000"
    networks:
      - default
      - proxy
    restart: always

  admin-panel:
    image: ${IMAGE_ADMIN:-fintech-admin:prod}
    env_file: .env
    environment:
      VIRTUAL_HOST: admin.msg.fintech-consult.ru
      LETSENCRYPT_HOST: admin.msg.fintech-consult.ru
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      VIRTUAL_PORT: 80
    expose:
      - "80"
    networks:
      - default
      - proxy
    restart: always

  user-panel:
    image: ${IMAGE_USER:-fintech-user:prod}
    env_file: .env
    environment:
      VIRTUAL_HOST: msg.fintech-consult.ru
      LETSENCRYPT_HOST: msg.fintech-consult.ru
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      VIRTUAL_PORT: 80
    expose:
      - "80"
    networks:
      - default
      - proxy
    restart: always

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: messenger
      POSTGRES_PASSWORD: messenger
      POSTGRES_DB: messenger
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    restart: always

volumes:
  postgres_data:
  redis_data:

networks:
  proxy:
    external: true
    name: app_default